# Generated by Django 4.2.5 on 2023-10-05 18:44

from django.db import migrations, models
import os

def create_data_144(apps, schema_editor):

    for mod in ['Name', 'Mouth', 'Eyes', 'Antenna']:

        Model = apps.get_model('avatars', f'{mod}144')

        for image_file in os.listdir(f'media/image/144/{mod}/'):

            if image_file[0] == '+':

                create = Model()
                create.id = int(image_file.split('_')[1])
                create.name = image_file.split('_')[-1].split('.')[0]
                create.element1 = f'media/image/144/{mod}/{image_file}'

                if image_file[1] == '-':
                    create.element1 = f'media/image/144/{mod}/-+{image_file[2:]}'

                create.save()


def create_data_720(apps, schema_editor):

    for mod in ['Name', 'Mouth', 'Eyes', 'Antenna']:

        Model = apps.get_model('avatars', f'{mod}720')

        for image_file in os.listdir(f'media/image/720/{mod}/'):

            if image_file[0] == '+':

                create = Model()
                create.id = int(image_file.split('_')[1])
                create.name = image_file.split('_')[-1].split('.')[0]
                create.element1 = f'media/image/720/{mod}/{image_file}'

                if image_file[1] == '-':
                    create.element2 = f'media/image/720/{mod}/-+{image_file[2:]}'

                create.save()





class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antenna144',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('element1', models.ImageField(upload_to='elements/name/')),
                ('element2', models.ImageField(upload_to='elements/name/')),
            ],
        ),
        migrations.CreateModel(
            name='Antenna720',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('element1', models.ImageField(upload_to='elements/name/')),
                ('element2', models.ImageField(upload_to='elements/name/')),
            ],
        ),
        migrations.CreateModel(
            name='Eyes144',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('element1', models.ImageField(upload_to='elements/name/')),
                ('element2', models.ImageField(upload_to='elements/name/')),
            ],
        ),
        migrations.CreateModel(
            name='Eyes720',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('element1', models.ImageField(upload_to='elements/name/')),
                ('element2', models.ImageField(upload_to='elements/name/')),
            ],
        ),
        migrations.CreateModel(
            name='Mouth144',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('element1', models.ImageField(upload_to='elements/name/')),
                ('element2', models.ImageField(upload_to='elements/name/')),
            ],
        ),
        migrations.CreateModel(
            name='Mouth720',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('element1', models.ImageField(upload_to='elements/name/')),
                ('element2', models.ImageField(upload_to='elements/name/')),
            ],
        ),
        migrations.CreateModel(
            name='Name144',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('element1', models.ImageField(upload_to='elements/name/')),
                ('element2', models.ImageField(upload_to='elements/name/')),
            ],
        ),
        migrations.CreateModel(
            name='Name720',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('element1', models.ImageField(upload_to='elements/name/')),
                ('element2', models.ImageField(upload_to='elements/name/')),
            ],
        ),

        migrations.RunPython(create_data_144),
        migrations.RunPython(create_data_720),

    ]
